# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170507_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='picMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ts', models.DateTimeField(null=True)),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maps.Picture')),
            ],
        ),
    ]
