# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('weight', models.FloatField(null=True)),
                ('weightUnit', models.CharField(max_length=2, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Adventure')),
                ('parent', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maps.GearItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('asin', models.CharField(max_length=13, null=True)),
                ('weight', models.FloatField(null=True)),
                ('weightUnit', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gearitem',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.RefItems'),
        ),
    ]
