# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20170821_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gearpicture',
            old_name='defult',
            new_name='default',
        ),
    ]
