# Generated by Django 2.1.1 on 2018-09-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_gearpicturetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='filename',
        ),
    ]
